# Generated by Django 3.0.2 on 2020-01-29 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20200129_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
