# Generated by Django 3.0.2 on 2020-01-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20200129_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(default='', max_length=150),
        ),
    ]
