# Generated by Django 3.0.2 on 2020-01-26 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=84)),
                ('address_line2', models.CharField(blank=True, max_length=84)),
                ('town_city', models.CharField(blank=True, max_length=84)),
                ('county', models.CharField(blank=True, max_length=84)),
                ('postcode', models.CharField(blank=True, max_length=8)),
                ('country', models.CharField(blank=True, max_length=84)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
