# Generated by Django 3.0.2 on 2020-03-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200307_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_types',
            options={'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
    ]
