# Generated by Django 3.0.2 on 2020-04-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200307_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
